### PR TITLE
Interaction example

### PR DESCRIPTION
**Pull request by kikoseijo**
Check this out,

This is what I meant to have done, seems working.

Interactions its a pattern I found to be great to hold the heavy load of big savings or updates with lots of related fields, checks, and so, I think its best to have the save and update on a separate file. This pattern I saw in the Spark project from Laravel and  I loved and absorbed.

Last thing I'm missing now its to be able to declare the params of a mutation direct from the model type, because with large amount of fields its silly to write them twice and its easier to have type extend.

I see you have the Input Type, but didn't see it implemented and thus don't know the way to make that work.

### CODE REVIEW

**Comment by kikoseijo** [comment]
Here, save you some coding

```graphql
mutation CreateUserMutation(
  $name: String
  $email: String!
  $password: String!
) {
  createUser(email: $email, name: $name, password: $password) {
    id
  }
}
```

```json
{
  "name": "The GraphQL boss",
  "email": "example@exsample.org",
  "password": "secret"
}
```

I did not make name required on purpose. email will fail also, but...


screen shot 2018-03-23 at 22 56 53

**Comment by chrissm79** [comment]
@kikoseijo I like this directive! I have a `@create` directive that will take a model and autofill it, you can also use the `@inject` directive to fill in arguments you might want to prevent being filled by the client. So you can do something like this:

```graphql
type Mutation {
  createUser(
    # This isn't necessary since we're injecting it with the @inject directive
    # company_id: Int! 
    name: String!  @validate(rules: ["min:2"])
    email: String!  @validate(rules: ["email", "unique:users,email"])
    password: String! @validate(rules: ["confirmed", "min:6"])
    # This is ignored if it's not included in the $fillable property (on App\User)
    password_confirmation: String!
    ): User 
      @create(model: "App\\User") 
      #inject the authenticated user's company_id into the newly created model
      @inject(context: "user.company_id" name: "company_id")
}
```

I can update it to assume that the user is creating an eloquent model and using the `fill` method, but also allow a `class` argument to be added so you can use any class you want to to create the data. Would that accomplish what you're trying to do? 

Btw, I really like the `ClassNamespace@method` syntax, very Laravelish... I think I'll go back through and remove the `method` arguments on any directives I currently have or just default to this.

**Comment by kikoseijo** [comment]
What about extending with superpowers what you have:

The create directive will search for `Model::$rules`, and if they exist will run the validation, saves you some typing.

The field directive* will search for a method called `validator` and if it founds will run validations, if pass or not found will run handle if no method specified. (Some Laravel magic)

* field directive in a mutation sounds strange, at the end of the day its same thing. Ill go for something more descriptive like call, interact, easier to remember and if you want them 3 extend by parent but perform a different step depending which one you want. (, ...., just a thought.)

**Comment by kikoseijo** [comment]
Another thought, when you have a relationship your create or update methods are no longer valid unless you do some logic on the event directive. Am I right? and take the request() from the global, ..

Somehow you need more control over this methods or alternative methods like run after update.

I personally won't take that weight over my shoulders, for a library, ill leave the logic to the users.

**Pull request closed without merging**
